packages:
  - packages/*

allowBuilds:
  '@dcloudio/hbuilderx-cli': false
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: false
  vue-demi: true
  workerd: true
onlyBuiltDependencies:
  - '@weapp-tailwindcss/merge'
minimumReleaseAge: 0
versioning:
  fixed:
    - - create-uni-app-tailwindcss
  ignore:
    - uni-app-tailwindcss-template-default
  changelog:
    storage: repository
